{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "native-gradle-plugin",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-gradle-plugin-1.1.3.jar",
          "url": "native-gradle-plugin-1.1.3.jar",
          "size": 136868,
          "sha512": "4341eb7e9fa2c4bf423493e7d9f9532d2d16091ae6cd04dd82eac1c2c2409195572febad2fdf8c5ec9b1f64e29f9add6823802d923e81db6b52a151964baf07f",
          "sha256": "0d447028e56c6604bcc706fecb7d00acdbab28861d5a02aae65e4dddab5c6911",
          "sha1": "2cb4588820be449c99315ec46e4102a1c9d0e1d8",
          "md5": "9b6920bb1f141fcf37c37cfb6543e79d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.graalvm.buildtools",
          "module": "utils",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.graalvm.buildtools",
          "module": "graalvm-reachability-metadata",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "native-gradle-plugin-1.1.3.jar",
          "url": "native-gradle-plugin-1.1.3.jar",
          "size": 136868,
          "sha512": "4341eb7e9fa2c4bf423493e7d9f9532d2d16091ae6cd04dd82eac1c2c2409195572febad2fdf8c5ec9b1f64e29f9add6823802d923e81db6b52a151964baf07f",
          "sha256": "0d447028e56c6604bcc706fecb7d00acdbab28861d5a02aae65e4dddab5c6911",
          "sha1": "2cb4588820be449c99315ec46e4102a1c9d0e1d8",
          "md5": "9b6920bb1f141fcf37c37cfb6543e79d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-gradle-plugin-1.1.3-javadoc.jar",
          "url": "native-gradle-plugin-1.1.3-javadoc.jar",
          "size": 287056,
          "sha512": "9b159c1ac9ab25571bbe9d1f6f44a06ffa60de9b3b53597eb43a239092deedad4f33ce514d0f21fb2a55c10b71536ff42b158e3fe167da914c9455a725addb87",
          "sha256": "16b674e791c05a059d7a81e3d06ce767ca6dc6eaca5d8dc9770e2a37c73d1b45",
          "sha1": "31f8b0c9223cfe76f519a94495a7d13d1833dca9",
          "md5": "bb333e8da1ab934c2f71bd6a08a2e652"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-gradle-plugin-1.1.3-sources.jar",
          "url": "native-gradle-plugin-1.1.3-sources.jar",
          "size": 106171,
          "sha512": "2be97042060f44c9536ad7c86b4d0df7726a3f9aef7730be8c34eabbffb70ea9e6c0e1db625b49dcbc685b33a815a18d23041e2e10ea99d821c404c917041c0f",
          "sha256": "3974a531fce3ed126e20d918be1def7242c1c2815a3f53c9fc637f55a975128e",
          "sha1": "e5aa2d9affa50c7714ce808e7e8920f99d87558c",
          "md5": "14f0cc55826d589fd94a1e00e8f5d0df"
        }
      ]
    }
  ]
}
