// Code generated from the shell's theme catalog. DO NOT EDIT.
//
// One-off extraction of the static theme palettes: for each named theme, its
// colour roles keyed by the camelCase token names Theme.qml resolves. The two
// dynamic variants (Default, Wallpaper) carry no static palette and are absent
// here -- the daemon clears themePalette for them. Regenerate by re-running the
// extractor against the shell's theme catalog when the catalog changes.

package main

// themePalettes maps each static theme name (the value stored under theme.theme)
// to its palette: colour-role token -> hex. On load and on any patch that changes
// theme.theme, the daemon copies the selected theme's palette into the passthrough
// themePalette key, and the pill binds Theme.namedScheme to it to repaint live.
var themePalettes = map[string]map[string]string{
	"Catppuccin Mocha": {
		"surface":                 "#1e1e2e",
		"onSurface":               "#cdd6f4",
		"surfaceVariant":          "#313244",
		"onSurfaceVariant":        "#bac2de",
		"surfaceContainerLowest":  "#11111b",
		"surfaceContainerLow":     "#181825",
		"surfaceContainer":        "#313244",
		"surfaceContainerHigh":    "#45475a",
		"surfaceContainerHighest": "#585b70",
		"inverseSurface":          "#cdd6f4",
		"inverseOnSurface":        "#313244",
		"surfaceTint":             "#b4befe",
		"primary":                 "#b4befe",
		"onPrimary":               "#313244",
		"primaryContainer":        "#313244",
		"onPrimaryContainer":      "#b4befe",
		"secondary":               "#f2cdcd",
		"onSecondary":             "#313244",
		"secondaryContainer":      "#313244",
		"onSecondaryContainer":    "#f2cdcd",
		"tertiary":                "#94e2d5",
		"onTertiary":              "#313244",
		"tertiaryContainer":       "#313244",
		"onTertiaryContainer":     "#94e2d5",
		"error":                   "#f38ba8",
		"onError":                 "#313244",
		"errorContainer":          "#313244",
		"onErrorContainer":        "#f38ba8",
		"outline":                 "#a6adc8",
		"outlineVariant":          "#6c7086",
		"background":              "#1e1e2e",
		"onBackground":            "#cdd6f4",
		"shadow":                  "#11111b",
		"scrim":                   "#11111b",
	},
	"Dracula": {
		"surface":                 "#282A36",
		"onSurface":               "#F8F8F2",
		"surfaceVariant":          "#44475A",
		"onSurfaceVariant":        "#F8F8F2",
		"surfaceContainerLowest":  "#282A36",
		"surfaceContainerLow":     "#282A36",
		"surfaceContainer":        "#44475A",
		"surfaceContainerHigh":    "#44475A",
		"surfaceContainerHighest": "#6272A4",
		"inverseSurface":          "#F8F8F2",
		"inverseOnSurface":        "#282A36",
		"surfaceTint":             "#BD93F9",
		"primary":                 "#BD93F9",
		"onPrimary":               "#282A36",
		"primaryContainer":        "#44475A",
		"onPrimaryContainer":      "#BD93F9",
		"secondary":               "#FF79C6",
		"onSecondary":             "#282A36",
		"secondaryContainer":      "#44475A",
		"onSecondaryContainer":    "#FF79C6",
		"tertiary":                "#8BE9FD",
		"onTertiary":              "#282A36",
		"tertiaryContainer":       "#44475A",
		"onTertiaryContainer":     "#8BE9FD",
		"error":                   "#FF5555",
		"onError":                 "#282A36",
		"errorContainer":          "#44475A",
		"onErrorContainer":        "#FF5555",
		"outline":                 "#6272A4",
		"outlineVariant":          "#44475A",
		"background":              "#282A36",
		"onBackground":            "#F8F8F2",
		"shadow":                  "#282A36",
		"scrim":                   "#282A36",
	},
	"Everforest Dark Medium": {
		"surface":                 "#232A2E",
		"onSurface":               "#D3C6AA",
		"surfaceVariant":          "#343F44",
		"onSurfaceVariant":        "#9DA9A0",
		"surfaceContainerLowest":  "#232A2E",
		"surfaceContainerLow":     "#2D353B",
		"surfaceContainer":        "#343F44",
		"surfaceContainerHigh":    "#3D484D",
		"surfaceContainerHighest": "#475258",
		"inverseSurface":          "#D3C6AA",
		"inverseOnSurface":        "#232A2E",
		"surfaceTint":             "#7FBBB3",
		"primary":                 "#A7C080",
		"onPrimary":               "#232A2E",
		"primaryContainer":        "#425047",
		"onPrimaryContainer":      "#A7C080",
		"secondary":               "#7FBBB3",
		"onSecondary":             "#232A2E",
		"secondaryContainer":      "#3A515D",
		"onSecondaryContainer":    "#7FBBB3",
		"tertiary":                "#83C092",
		"onTertiary":              "#232A2E",
		"tertiaryContainer":       "#425047",
		"onTertiaryContainer":     "#83C092",
		"error":                   "#E67E80",
		"onError":                 "#232A2E",
		"errorContainer":          "#514045",
		"onErrorContainer":        "#E67E80",
		"outline":                 "#7A8478",
		"outlineVariant":          "#3D484D",
		"background":              "#232A2E",
		"onBackground":            "#D3C6AA",
		"shadow":                  "#232A2E",
		"scrim":                   "#232A2E",
	},
	"Gruvbox Dark Medium": {
		"surface":                 "#282828",
		"onSurface":               "#EBDBB2",
		"surfaceVariant":          "#3C3836",
		"onSurfaceVariant":        "#D5C4A1",
		"surfaceContainerLowest":  "#282828",
		"surfaceContainerLow":     "#3C3836",
		"surfaceContainer":        "#504945",
		"surfaceContainerHigh":    "#665C54",
		"surfaceContainerHighest": "#7C6F64",
		"inverseSurface":          "#EBDBB2",
		"inverseOnSurface":        "#282828",
		"surfaceTint":             "#83A598",
		"primary":                 "#83A598",
		"onPrimary":               "#282828",
		"primaryContainer":        "#504945",
		"onPrimaryContainer":      "#83A598",
		"secondary":               "#B8BB26",
		"onSecondary":             "#282828",
		"secondaryContainer":      "#504945",
		"onSecondaryContainer":    "#B8BB26",
		"tertiary":                "#8EC07C",
		"onTertiary":              "#282828",
		"tertiaryContainer":       "#504945",
		"onTertiaryContainer":     "#8EC07C",
		"error":                   "#FB4934",
		"onError":                 "#282828",
		"errorContainer":          "#504945",
		"onErrorContainer":        "#FB4934",
		"outline":                 "#928374",
		"outlineVariant":          "#504945",
		"background":              "#282828",
		"onBackground":            "#EBDBB2",
		"shadow":                  "#282828",
		"scrim":                   "#282828",
	},
	"Kanagawa Wave": {
		"surface":                 "#1F1F28",
		"onSurface":               "#DCD7BA",
		"surfaceVariant":          "#2A2A37",
		"onSurfaceVariant":        "#C8C093",
		"surfaceContainerLowest":  "#16161D",
		"surfaceContainerLow":     "#181820",
		"surfaceContainer":        "#2A2A37",
		"surfaceContainerHigh":    "#363646",
		"surfaceContainerHighest": "#54546D",
		"inverseSurface":          "#DCD7BA",
		"inverseOnSurface":        "#2A2A37",
		"surfaceTint":             "#7E9CD8",
		"primary":                 "#7E9CD8",
		"onPrimary":               "#2A2A37",
		"primaryContainer":        "#223249",
		"onPrimaryContainer":      "#7FB4CA",
		"secondary":               "#957FB8",
		"onSecondary":             "#2A2A37",
		"secondaryContainer":      "#2A2A37",
		"onSecondaryContainer":    "#938AA9",
		"tertiary":                "#7AA89F",
		"onTertiary":              "#2A2A37",
		"tertiaryContainer":       "#2A2A37",
		"onTertiaryContainer":     "#6A9589",
		"error":                   "#E82424",
		"onError":                 "#2A2A37",
		"errorContainer":          "#43242B",
		"onErrorContainer":        "#E46876",
		"outline":                 "#938AA9",
		"outlineVariant":          "#54546D",
		"background":              "#1F1F28",
		"onBackground":            "#DCD7BA",
		"shadow":                  "#16161D",
		"scrim":                   "#16161D",
	},
	"Nord Dark": {
		"surface":                 "#2E3440",
		"onSurface":               "#ECEFF4",
		"surfaceVariant":          "#3B4252",
		"onSurfaceVariant":        "#D8DEE9",
		"surfaceContainerLowest":  "#2E3440",
		"surfaceContainerLow":     "#2E3440",
		"surfaceContainer":        "#3B4252",
		"surfaceContainerHigh":    "#434C5E",
		"surfaceContainerHighest": "#4C566A",
		"inverseSurface":          "#ECEFF4",
		"inverseOnSurface":        "#2E3440",
		"surfaceTint":             "#88C0D0",
		"primary":                 "#88C0D0",
		"onPrimary":               "#2E3440",
		"primaryContainer":        "#3B4252",
		"onPrimaryContainer":      "#88C0D0",
		"secondary":               "#81A1C1",
		"onSecondary":             "#2E3440",
		"secondaryContainer":      "#3B4252",
		"onSecondaryContainer":    "#81A1C1",
		"tertiary":                "#8FBCBB",
		"onTertiary":              "#2E3440",
		"tertiaryContainer":       "#3B4252",
		"onTertiaryContainer":     "#8FBCBB",
		"error":                   "#BF616A",
		"onError":                 "#2E3440",
		"errorContainer":          "#3B4252",
		"onErrorContainer":        "#BF616A",
		"outline":                 "#4C566A",
		"outlineVariant":          "#434C5E",
		"background":              "#2E3440",
		"onBackground":            "#ECEFF4",
		"shadow":                  "#2E3440",
		"scrim":                   "#2E3440",
	},
	"One Dark": {
		"surface":                 "#282C34",
		"onSurface":               "#ABB2BF",
		"surfaceVariant":          "#31363F",
		"onSurfaceVariant":        "#828997",
		"surfaceContainerLowest":  "#16181D",
		"surfaceContainerLow":     "#1F2228",
		"surfaceContainer":        "#31363F",
		"surfaceContainerHigh":    "#3A3F4B",
		"surfaceContainerHighest": "#434956",
		"inverseSurface":          "#ABB2BF",
		"inverseOnSurface":        "#31363F",
		"surfaceTint":             "#61AFEF",
		"primary":                 "#61AFEF",
		"onPrimary":               "#31363F",
		"primaryContainer":        "#31363F",
		"onPrimaryContainer":      "#61AFEF",
		"secondary":               "#C678DD",
		"onSecondary":             "#31363F",
		"secondaryContainer":      "#31363F",
		"onSecondaryContainer":    "#C678DD",
		"tertiary":                "#56B6C2",
		"onTertiary":              "#31363F",
		"tertiaryContainer":       "#31363F",
		"onTertiaryContainer":     "#56B6C2",
		"error":                   "#E06C75",
		"onError":                 "#31363F",
		"errorContainer":          "#31363F",
		"onErrorContainer":        "#E06C75",
		"outline":                 "#636D83",
		"outlineVariant":          "#5C6370",
		"background":              "#282C34",
		"onBackground":            "#ABB2BF",
		"shadow":                  "#16181D",
		"scrim":                   "#16181D",
	},
	"Rose Pine": {
		"surface":                 "#191724",
		"onSurface":               "#E0DEF4",
		"surfaceVariant":          "#1F1D2E",
		"onSurfaceVariant":        "#908CAA",
		"surfaceContainerLowest":  "#191724",
		"surfaceContainerLow":     "#1F1D2E",
		"surfaceContainer":        "#26233A",
		"surfaceContainerHigh":    "#403D52",
		"surfaceContainerHighest": "#524F67",
		"inverseSurface":          "#E0DEF4",
		"inverseOnSurface":        "#191724",
		"surfaceTint":             "#C4A7E7",
		"primary":                 "#C4A7E7",
		"onPrimary":               "#191724",
		"primaryContainer":        "#26233A",
		"onPrimaryContainer":      "#C4A7E7",
		"secondary":               "#9CCFD8",
		"onSecondary":             "#191724",
		"secondaryContainer":      "#26233A",
		"onSecondaryContainer":    "#9CCFD8",
		"tertiary":                "#EBBCBA",
		"onTertiary":              "#191724",
		"tertiaryContainer":       "#26233A",
		"onTertiaryContainer":     "#EBBCBA",
		"error":                   "#EB6F92",
		"onError":                 "#191724",
		"errorContainer":          "#26233A",
		"onErrorContainer":        "#EB6F92",
		"outline":                 "#6E6A86",
		"outlineVariant":          "#403D52",
		"background":              "#191724",
		"onBackground":            "#E0DEF4",
		"shadow":                  "#191724",
		"scrim":                   "#191724",
	},
	"Solarized Dark": {
		"surface":                 "#002b36",
		"onSurface":               "#93a1a1",
		"surfaceVariant":          "#073642",
		"onSurfaceVariant":        "#839496",
		"surfaceContainerLowest":  "#00212b",
		"surfaceContainerLow":     "#003847",
		"surfaceContainer":        "#073642",
		"surfaceContainerHigh":    "#586e75",
		"surfaceContainerHighest": "#657b83",
		"inverseSurface":          "#eee8d5",
		"inverseOnSurface":        "#073642",
		"surfaceTint":             "#268bd2",
		"primary":                 "#268bd2",
		"onPrimary":               "#073642",
		"primaryContainer":        "#073642",
		"onPrimaryContainer":      "#268bd2",
		"secondary":               "#2aa198",
		"onSecondary":             "#073642",
		"secondaryContainer":      "#073642",
		"onSecondaryContainer":    "#2aa198",
		"tertiary":                "#b58900",
		"onTertiary":              "#073642",
		"tertiaryContainer":       "#073642",
		"onTertiaryContainer":     "#b58900",
		"error":                   "#dc322f",
		"onError":                 "#073642",
		"errorContainer":          "#073642",
		"onErrorContainer":        "#dc322f",
		"outline":                 "#839496",
		"outlineVariant":          "#586e75",
		"background":              "#002b36",
		"onBackground":            "#93a1a1",
		"shadow":                  "#00212b",
		"scrim":                   "#00212b",
	},
	"Tokyo Night": {
		"surface":                 "#1a1b26",
		"onSurface":               "#a9b1d6",
		"surfaceVariant":          "#2f3549",
		"onSurfaceVariant":        "#9aa5ce",
		"surfaceContainerLowest":  "#101014",
		"surfaceContainerLow":     "#16161e",
		"surfaceContainer":        "#2f3549",
		"surfaceContainerHigh":    "#414868",
		"surfaceContainerHighest": "#565f89",
		"inverseSurface":          "#c0caf5",
		"inverseOnSurface":        "#2f3549",
		"surfaceTint":             "#7aa2f7",
		"primary":                 "#7aa2f7",
		"onPrimary":               "#2f3549",
		"primaryContainer":        "#2f3549",
		"onPrimaryContainer":      "#7aa2f7",
		"secondary":               "#bb9af7",
		"onSecondary":             "#2f3549",
		"secondaryContainer":      "#2f3549",
		"onSecondaryContainer":    "#bb9af7",
		"tertiary":                "#73daca",
		"onTertiary":              "#2f3549",
		"tertiaryContainer":       "#2f3549",
		"onTertiaryContainer":     "#73daca",
		"error":                   "#f7768e",
		"onError":                 "#2f3549",
		"errorContainer":          "#2f3549",
		"onErrorContainer":        "#f7768e",
		"outline":                 "#9aa5ce",
		"outlineVariant":          "#565f89",
		"background":              "#1a1b26",
		"onBackground":            "#a9b1d6",
		"shadow":                  "#101014",
		"scrim":                   "#101014",
	},
}

// themeCatalogNames lists the static theme names in sorted order, for stable
// validation of theme.theme and deterministic error messages.
var themeCatalogNames = []string{
	"Catppuccin Mocha",
	"Dracula",
	"Everforest Dark Medium",
	"Gruvbox Dark Medium",
	"Kanagawa Wave",
	"Nord Dark",
	"One Dark",
	"Rose Pine",
	"Solarized Dark",
	"Tokyo Night",
}
